### ISSUE TITLE
AttributeError for yapi GUI

### ISSUE THREAD

**Issue by Wabri** [YetAnotherPackageInstaller/YAPI#37]
I installed all the dependencies, but when i tried to run this is the output:
```
Traceback (most recent call last):
  File "/home/wabri/git/YAPI/env/lib/python3.5/site-packages/toga_gtk/app.py", line 116, in _startup
    self.startup()
  File "/home/wabri/git/YAPI/env/lib/python3.5/site-packages/toga/interface/app.py", line 144, in startup
    self.main_window.content = self._startup_method(self)
  File "/home/wabri/git/YAPI/user_interface.py", line 41, in build
    box.style.update(direction=COLUMN, padding_top=10)
AttributeError: 'CSS' object has no attribute 'update'
```
and this is the line where the error was thorwn:
https://github.com/YetAnotherPackageInstaller/YAPI/blob/bc1c63ae5ddb8b7fde73dba4207578d5e7114bbf/user_interface.py#L41

**Comment by IanDuncanT** [comment]
You need to install toga and it's components from the github repository. The code that is erroring is fixed in a new commit that is not in a release yet. I have not received errors from this repository yet. Follow the instructions at https://toga.readthedocs.io/en/latest/how-to/contribute.html to install, except don't fork the repository, but instead clone it directly. When the next version of toga is released, there should be no need to install from source.

**Comment by IanDuncanT** [comment]
I am going to update the readme to include instructions about installing toga from source.
