### ISSUE TITLE
Install YAPI

### ISSUE THREAD

**Issue by Wabri** [YetAnotherPackageInstaller/YAPI#42]
How can we manage the installation yapi on a new computer?
How about new script called install.sh to run with:
`wget https://raw.githubusercontent.com/Wabri/YAPI/install.sh -O - | sudo bash -`
something like this:
```
git clone https://github.com/Wabri/YAPI.git --depth 1
sudo ln -s ~/YAPI/yapi.sh /usr/local/bin/yapi
```

**Comment by IanDuncanT** [comment]
I saw the solution in a pull request and I like that solution to install. I only caution about where they put the script and where it installs to. It could have an issue of pulling to a directory in use. For example if they have ~/YAPI/scrips/install.sh and are installing it, it could error. It should be fine once the file paths are fixed in the pull request. You can remove my branch and issue for alias once the soflinking works.
